#!/usr/bin/env Rscript --no-save --no-restore

work_path <- normalizePath("{{ work_path }}", winslash = "/")
ct_path0 <- normalizePath("{{ ct_path }}", mustWork = TRUE, winslash = "/")
mri_path0 <- normalizePath("{{ mri_path }}", mustWork = TRUE, winslash = "/")
reg_type <- "{{ reg_type }}"
cost <- "{{ cost }}"
interp <- "{{ interp }}"
max_side <- 384
verbose <- TRUE

coreg_path <- file.path(work_path, "coregistration")
deriv_path <- file.path(work_path, "derivative")

# Register first: an error stops the script here, before the configuration
# file or the copies in `derivative` change
reg_results <- ravecore::reg3d_rigid(
  ct_path = ct_path0,
  mri_path = mri_path0,
  coreg_path = coreg_path,
  reg_type = reg_type,
  cost = cost,
  interp = interp,
  max_side = max_side,
  verbose = verbose
)

if (!dir.exists(deriv_path)) {
  dir.create(deriv_path, showWarnings = FALSE, recursive = TRUE)
}

# Write down configuration files
outputs <- list(
  ct_in_t1 = list(
    type = "nifti",
    path = "./coregistration/ct_in_t1.nii.gz",
    backup = "./derivative/ct_in_t1.nii.gz",
    comment = "re-sampled CT; the resolution is the same as reference MRI"
  ),
  CT_IJK_to_MR_RAS = list(
    type = "transform",
    dimension = "4x4",
    path = "./coregistration/CT_IJK_to_MR_RAS.txt",
    backup = "./derivative/transform-ctIJK2mrRAS.txt",
    transform_from = list(
      volume = "input_image",
      coordinate_system = "IJK"
    ),
    transform_to = list(
      volume = "reference_image",
      space = "scanner",
      coordinate_system = "RAS"
    ),
    comment = "From voxel IJK coordinate of ./coregistration/CT_RAW.nii.gz to MRI scanner RAS coordinate"
  ),
  CT_RAS_to_MR_RAS = list(
    type = "transform",
    dimension = "4x4",
    path = "./coregistration/CT_RAS_to_MR_RAS.txt",
    backup = "./derivative/transform-ctRAS2mrRAS.txt",
    transform_from = list(
      volume = "input_image",
      space = "scanner (CT)",
      coordinate_system = "RAS"
    ),
    transform_to = list(
      volume = "reference_image",
      space = "scanner",
      coordinate_system = "RAS"
    ),
    comment = "From CT scanner RAS coordinate to MRI scanner RAS coordinate"
  ),
  registration = list(
    type = "ravetools-registration",
    path = "./coregistration/reg3d/reg3d.dcf",
    comment = "ravetools registration record of the full-resolution images; ANTs-style affine in reg3d0GenericAffine.mat"
  )
)
if (isTRUE(reg_results$resampled[["CT"]])) {
  outputs$CT_ORIG <- list(
    type = "nifti",
    path = "./coregistration/CT_ORIG.nii.gz",
    comment = "original CT; CT_RAW.nii.gz is this image down-sampled for viewers (same field of view)"
  )
}
if (isTRUE(reg_results$resampled[["MRI"]])) {
  outputs$MRI_ORIG <- list(
    type = "nifti",
    path = "./coregistration/MRI_ORIG.nii.gz",
    comment = "original MRI; MRI_reference.nii.gz is this image down-sampled for viewers (same field of view)"
  )
}

# Keep a copy of the previous configuration
ravecore::backup_file(file.path(deriv_path, "conf-coregistration.yaml"),
                      remove = FALSE, quiet = TRUE)

ieegio::io_write_yaml(
  con = file.path(deriv_path, "conf-coregistration.yaml"),
  list(
    `Heads up` = "Do NOT edit this file",
    profile = "CT coregister to MRI",
    work_path = work_path,
    timestamp = strftime(Sys.time(), "%a %b %d %H:%M:%S %Z %Y", tz = "UTC"),
    command = list(
      comment = "This is R function call",
      execute = "ravecore::reg3d_rigid",
      arguments = list(
        reg_type = reg_type,
        cost = cost,
        interp = interp,
        max_side = max_side
      )
    ),
    input_image = list(
      type = "nifti",
      path = ct_path0,
      backup = c(
        "./derivative/CT_RAW.nii.gz",
        "./coregistration/CT_RAW.nii.gz"
      ),
      comment = "original CT image file"
    ),
    reference_image = list(
      type = "nifti",
      path = mri_path0,
      backup = c(
        "./coregistration/MRI_reference.nii.gz"
      ),
      comment = "Reference MR image file, the CT is aligned to this reference image"
    ),
    outputs = outputs
  )
)

# Finalize
for (file_name in c("ct_in_t1.nii.gz", "CT_RAW.nii.gz", "MRI_reference.nii.gz")) {
  file.copy(
    from = file.path(coreg_path, file_name),
    to = file.path(deriv_path, file_name),
    overwrite = TRUE,
    recursive = FALSE,
    copy.mode = TRUE,
    copy.date = TRUE
  )
}
file.copy(
  from = file.path(coreg_path, "CT_IJK_to_MR_RAS.txt"),
  to = file.path(deriv_path, "transform-ctIJK2mrRAS.txt"),
  overwrite = TRUE,
  recursive = FALSE,
  copy.mode = TRUE,
  copy.date = TRUE
)
file.copy(
  from = file.path(coreg_path, "CT_RAS_to_MR_RAS.txt"),
  to = file.path(deriv_path, "transform-ctRAS2mrRAS.txt"),
  overwrite = TRUE,
  recursive = FALSE,
  copy.mode = TRUE,
  copy.date = TRUE
)



## END OF RAVE Script: CT MR rigid co-registration via ravetools (YAEL-reg3d)
