# ravecore::cmd_run_yael_preprocess(subject = "YAEL/Snorlax", t1w_path = '/Users/dipterix/Dropbox (Personal)/projects/macaque/native_acpc_aligned.nii.gz', normalize_template = "nmt_v2_0_acpc_asym", normalize_affine = '/Users/dipterix/Library/Application Support/org.R-project.R/R/rpyANTs/templates/nmt_v2_0_acpc_asym/I4.mat', verbose = TRUE, use_antspynet = FALSE, run_recon_all = FALSE)

# prepare_freesurfer_input("YAEL/Snorlax", rescale = 2)

xfm_template <- "MNI Transform File
% Generated by ravecore:::prepare_freesurfer_input for original image

Transform_Type = Linear;
Transform_ID = 1;
Invert_Flag = False;

Linear_Transform =
 {astr[1, 1]}  {astr[1, 2]}  {astr[1, 3]}  {astr[1, 4]}
 {astr[2, 1]}  {astr[2, 2]}  {astr[2, 3]}  {astr[2, 4]}
 {astr[3, 1]}  {astr[3, 2]}  {astr[3, 3]}  {astr[3, 4]};"

yael_macaque_step1 <- function(subject, t1w_path, template = "nmt_v2_0_acpc_asym", folder_name = "fs") {

  # DIPSAUS DEBUG START
  # subject <- ravecore::as_rave_subject("YAEL/Snorlax")
  # template <- "nmt_v2_0_acpc_asym"
  # folder_name <- "ants"
  # rescale=2
  # t1w_path='/Users/dipterix/Dropbox (Personal)/projects/macaque/native_acpc_aligned.nii.gz'
  # verbose=TRUE
  # folder_name = "fs"

  rescale <- 2

  subject <- as_rave_subject(subject, strict = FALSE)
  ravepipeline::logger("[A] 1. Initializing RAVE subject ", subject$subject_id)

  t1w_path <- path_abs(t1w_path)
  if (!grepl("\\.(nii|nii\\.gz)$", t1w_path, ignore.case = TRUE)) {
    t1w <- ieegio::read_volume(t1w_path)

    mri_input_root <- file_path(subject$imaging_path, "inputs", "MRI")
    dir_create2(mri_input_root)
    t1w_path <- file_path(mri_input_root, "MRI_for_fs.nii.gz")
    ieegio::write_volume(t1w, t1w_path)
    rm(t1w)
  }

  # Initialize paths to make the subject legit
  subject$initialize_paths(include_freesurfer = TRUE)

  # Make sure the template is downloaded
  ravepipeline::logger("[A] 2. Ensuring template ", template)
  template_path <- call_rpyants("ensure_template", template)

  # Suppress affine in YAEL normalization
  identity_mat_path <- file_path(template_path, "I4.mat")

  # Run YAEL normalization
  ravepipeline::logger("[B] Starting YAEL preprocess")
  yael_preprocess(
    subject = subject,
    t1w_path = t1w_path,
    normalize_template = template,
    normalize_affine = identity_mat_path,
    verbose = TRUE,
    use_antspynet = FALSE,
    add_surfaces = FALSE
  )
  # ravepipeline::logger("[B] YAEL preprocess done. Please cite: Wang Z, Magnotti JF, Zhang X, Beauchamp MS. YAEL: Your Advanced Electrode Localizer. Eneuro. 2023 Oct 1;10(10).", level = "success")

  # Prepare FreeSurfer folder
  fs_root <- file_path(subject$imaging_path, folder_name)
  ravepipeline::logger("[C] Preparing FreeSurfer folder under: ")
  ravepipeline::logger("    ", fs_root)

  if (file_exists(fs_root)) {
    backup_file(fs_root, remove = TRUE, quiet = TRUE)
  }

  # Create full FreeSurfer folder
  for (sub_dir in c("surf", "label", "scripts", "stats", "tmp", "touch", "trash", "mri/transforms", "mri/raw", "mri/orig")) {
    dir_create2(file_path(fs_root, sub_dir))
  }
  mri_dir  <- file_path(fs_root, "mri")
  surf_dir <- file_path(fs_root, "surf")
  raw_dir <- file_path(fs_root, "mri", "raw")

  yael_process <- as_yael_process(subject = subject)

  # T1.nii.gz
  ravepipeline::logger("[C] Saving mri/raw/T1.nii.gz")
  t1_path <- yael_process$get_input_image("T1w")
  file.copy(t1_path, file_path(raw_dir, "T1.nii.gz"))

  # brainmask.nii.gz
  ravepipeline::logger("[C] Morphing back from template: mri/raw/T1_brainmask.nii.gz")
  template_mask <- file_path(template_path, "T1_brainmask.nii.gz")
  native_mask <- yael_process$transform_image_from_template(template_mask, template_name = template)
  native_mask$to_file(file_path(raw_dir, "brainmask.nii.gz"))
  rm(native_mask)

  # aparc+aseg.nii.gz
  ravepipeline::logger("[C] Morphing back from template: mri/raw/aparc+aseg.nii.gz")
  fs_atlas_path <- file_path(template_path, "aparc+aseg.nii.gz")
  fs_atlas <- yael_process$transform_image_from_template(fs_atlas_path, template_name = template)
  fs_atlas$to_file(file_path(raw_dir, "aparc+aseg.nii.gz"))
  rm(fs_atlas)

  #
  ravepipeline::logger("[C] Saving mri/raw/*.xfm")
  map <- yael_process$get_template_mapping(template_name = template)
  affine <- map$template_to_native$transformlist[[1]]

  # This is the ANTs passive inverse transform from LPS to LPS
  affine <- rpyANTs::as_ANTsTransform(affine)
  affine <- diag(c(-1, -1, 1, 1)) %*% affine[] %*% diag(c(-1, -1, 1, 1))

  # write xfm
  astr <- format(affine, scientific = FALSE, digits = 8, trim = TRUE)
  xfm_raw <- ravepipeline::glue(xfm_template)
  writeLines(xfm_raw, file_path(raw_dir, "affine.xfm"))

  # rescale is linear in offset, but since we rescale both
  # template and native brain, the R-matrix does not change
  affine[1:3, 4] <- affine[1:3, 4] * rescale
  astr <- format(affine, scientific = FALSE, digits = 8, trim = TRUE)
  xfm_raw <- ravepipeline::glue(xfm_template)
  writeLines(xfm_raw, file_path(raw_dir, "affine_x2.xfm"))

  # ---- Load T1 and brain mask from raw/ ----------------------------
  ravepipeline::logger("[D] Auto-crop MRI, leaving 5-voxel margins")
  mask_raw <- ieegio::read_volume(file_path(raw_dir, "brainmask.nii.gz"))
  dims <- dim(mask_raw)[seq_len(3)]

  # Skull-strip: zero out voxels outside the brain mask; find the boundary
  mask_data <- array(mask_raw[drop = FALSE] > 0, dim = dims)

  # Erode the mask by 3 to avoid loading isolated points
  nz <- which(ravetools::grow_volume(mask_data, 3, threshold = 26) > 0, arr.ind = TRUE)
  lo   <- pmax(1L, apply(nz, 2, min) - 8L)
  hi   <- pmin(dims, apply(nz, 2, max) + 8L)
  rm(nz)

  ravepipeline::logger(sprintf("[D] Autocrop: [%s] -> [%s]",
                               paste(dims, collapse = "x"), paste(hi - lo + 1L, collapse = "x")))

  # Crop mask
  mask_data <- mask_data[lo[1]:hi[1], lo[2]:hi[2], lo[3]:hi[3], drop = FALSE]

  # Crop T1
  t1_raw   <- ieegio::read_volume(file_path(raw_dir, "T1.nii.gz"))
  vox2ras_raw <- t1_raw$transforms$vox2ras
  t1_data <- t1_raw[lo[1]:hi[1], lo[2]:hi[2], lo[3]:hi[3], drop = FALSE]
  # t1_data[mask_data <= 0] <- 0
  rm(t1_raw)

  # Crop aparc+aseg
  aparc_raw <- ieegio::read_volume(file_path(raw_dir, "aparc+aseg.nii.gz"))
  aparc_data <- aparc_raw[lo[1]:hi[1], lo[2]:hi[2], lo[3]:hi[3], drop = FALSE]
  aparc_data <- array(as.integer(aparc_data), dim(aparc_data))
  rm(aparc_raw)


  # Shift affine origin by the crop offset (0-based voxel units -> mm)
  vox2ras <- vox2ras_raw
  vox2ras[1:3, 4] <- vox2ras[1:3, 4] + vox2ras[1:3, 1:3] %*% (lo - 1L)

  # # Intensity truncation (1%-99% of non-zero brain voxels)
  # message("[2/3] Truncating intensities (1%-99%)...")
  # brain_vals <- t1_crop_data[t1_crop_data > 0]
  # qs <- quantile(brain_vals, c(0.01, 0.99), na.rm = TRUE)
  # t1_final_data <- t1_crop_data
  # nz_mask <- t1_final_data > 0
  # t1_final_data[nz_mask] <- pmax(pmin(t1_final_data[nz_mask], qs[[2]]), qs[[1]])
  # t1_final <- ieegio::as_ieegio_volume(t1_final_data, vox2ras = crop_vox2ras)
  # t1_mask_final <- ieegio::as_ieegio_volume(t1_mask_crop_data, vox2ras = crop_vox2ras)
  # if (has_aparc) {
  #   aparc_final <- ieegio::as_ieegio_volume(aparc_crop_data, vox2ras = crop_vox2ras)
  # }
  #
  # ieegio::write_volume(t1_final, file_path(target_raw, "crop.nii.gz"))
  # ieegio::write_volume(t1_mask_final, file_path(target_raw, "crop_brainmask.nii.gz"))
  # if (has_aparc) {
  #   ieegio::write_volume(aparc_final, file_path(target_raw, "crop_aparc+aseg.nii.gz"))
  # }

  # save cropped images
  ieegio::write_volume(t1_data, format = "nifti", vox2ras = vox2ras,
                       con = file_path(raw_dir, "T1_cropped.nii.gz"))
  ieegio::write_volume(mask_data, format = "nifti", vox2ras = vox2ras,
                       con = file_path(raw_dir, "brainmask_cropped.nii.gz"))
  ieegio::write_volume(aparc_data, format = "nifti", vox2ras = vox2ras,
                       con = file_path(raw_dir, "aparc+aseg_cropped.nii.gz"))

  # Fake-space: scale vox2ras so voxels read as 1 mm
  # The "fake-space trick": macaque brains at 0.5 mm are ~256 voxels but only
  # ~130 mm wide. FreeSurfer atlas tools assume ~256 mm FOV (human scale).
  # Forcing voxel sizes to 1 mm makes the 256-voxel grid appear as 256 mm
  ravepipeline::logger("[D] Inflate image RAS coordinates by x", rescale)

  vox2ras_rescaled <- diag(c(rescale, rescale, rescale, 1)) %*% vox2ras

  ieegio::write_volume(t1_data, format = "nifti", vox2ras = vox2ras_rescaled,
                       con = file_path(raw_dir, "T1_x2.nii.gz"))
  ieegio::write_volume(mask_data, format = "nifti", vox2ras = vox2ras_rescaled,
                       con = file_path(raw_dir, "brainmask_x2.nii.gz"))
  ieegio::write_volume(aparc_data, format = "nifti", vox2ras = vox2ras_rescaled,
                       con = file_path(raw_dir, "aparc+aseg_x2.nii.gz"))

  rm(t1_data, mask_data, aparc_data)

  vox_sizes_raw <- sqrt(colSums(vox2ras[1:3, 1:3]^2))
  vox_sizes_rescaled <- sqrt(colSums(vox2ras_rescaled[1:3, 1:3]^2))
  ravepipeline::logger(sprintf(
    "[D] Voxel size: %.2f x %.2f x %.2f mm -> %.2f x %.2f x %.2f mm",
    vox_sizes_raw[[1]], vox_sizes_raw[[2]], vox_sizes_raw[[3]],
    vox_sizes_rescaled[[1]], vox_sizes_rescaled[[2]], vox_sizes_rescaled[[3]]
  ))

  # ---- FreeSurfer part --------------------------------------------
  ravepipeline::logger("Normalization done. Please run the reconstruction step.", level = "success")


}


yael_macaque_step2 <- function(subject, template = "nmt_v2_0_acpc_asym", folder_name = "fs") {

  fshome <- cmd_freesurfer_home(error_on_missing = TRUE)
  subject <- as_rave_subject(subject, strict = TRUE)
  rescale <- 2

  imaging_path <- path_abs(subject$imaging_path, must_work = TRUE)
  if (!grepl("^[a-zA-Z0-9\\./\\\\_-]+$", imaging_path)) {
    symlink_root <- file_path(
      tools::R_user_dir("ravecore", which = "cache"),
      "FreeSurfer",
      subject$subject_code
    )
    if (file_exists(symlink_root)) {
      unlink(symlink_root, recursive = TRUE)
    }
    dir_create2(dirname(symlink_root))
    file.symlink(to = symlink_root, from = subject$imaging_path)
    imaging_path <- gsub("[\\\\/]+", "/", symlink_root)
  }

  fs_root <- file_path(imaging_path, folder_name)
  stopifnot(file_exists(fs_root))

  # Key component Paths
  template_path <- call_rpyants("ensure_template", template)
  lh_tif <- file_path(template_path, "lh.PREEMACS_34_v1.tif")
  rh_tif <- file_path(template_path, "rh.PREEMACS_34_v1.tif")
  mni305 <- file_path(fshome, "average", "mni305.cor.mgz")
  mri_dir  <- file_path(fs_root, "mri")
  surf_dir <- file_path(fs_root, "surf")

  # Cortical parcellation
  gca_gcs <- file_path(fshome, "average", "lh.DKaparc.atlas.acfb40.noaparc.i12.2016-08-02.gcs")
  if (!file_exists(gca_gcs)) {
    gcs_files <- list.files(file_path(fshome, "average"),
                            pattern = "^lh\\.DKaparc.*\\.gcs$", full.names = TRUE)
    if (length(gcs_files) == 0L) {
      stop("DK aparc GCS atlas not found under ", fshome, "/average/")
    }
    gca_gcs <- sort(gcs_files)[length(gcs_files)]
  }


  env_list <- list(
    "FREESURFER_HOME" = fshome,
    "SUBJECTS_DIR" = imaging_path,
    "YAEL_ROOT" = fs_root,
    "YAEL_DNAME" = folder_name,
    "DKT_GCA" = gca_gcs
  )

  run_freesurfer <- function(command, workdir = "", ...) {
    workdir_abs <- file_path(fs_root, workdir)

    command <- command[!startsWith(command, "#")]
    cmd <- sprintf('source "$FREESURFER_HOME/SetUpFreeSurfer.sh"\n\n%s', paste(command, collapse = "\n"))
    code <- rpymat::run_command(
      command = cmd,
      use_glue = FALSE,
      enable_conda = FALSE,
      env_list = env_list,
      workdir = workdir_abs,
      ...
    )
    stopifnot2(code == 0, msg = "FreeSurfer command error; see messages above.")
  }



  command <- c(
    # Copy T1_scaled
    'echo "====> Building mri/orig/001.mgz"',
    'mri_convert -i "${YAEL_ROOT}/mri/raw/T1_x2.nii.gz" -o "${YAEL_ROOT}/mri/orig/001.mgz"',

    # Conform
    'echo "====> Conform mri/orig/001.mgz -> mri/rawavg.mgz -> mri/T1.mgz"',
    'mri_convert -c "${YAEL_ROOT}/mri/orig/001.mgz" "${YAEL_ROOT}/mri/rawavg.mgz"',
    'cp -f "${YAEL_ROOT}/mri/rawavg.mgz" "${YAEL_ROOT}/mri/orig.mgz"',
    'cp -f "${YAEL_ROOT}/mri/rawavg.mgz" "${YAEL_ROOT}/mri/T1.mgz"',


    # Convert brainmask
    'mri_convert -c "${YAEL_ROOT}/mri/raw/brainmask_x2.nii.gz" "${YAEL_ROOT}/mri/brainmask_x2.auto.mgz"',

    # NU bias correction (FS 8 uses --i/--o named flags, not positional)
    'mri_nu_correct.mni --i "${YAEL_ROOT}/mri/orig.mgz" --o "${YAEL_ROOT}/mri/nu.mgz"'
  )

  run_freesurfer(command)


  # Rescale nu.mgz so the 85th-percentile brain intensity (WM) = 110.
  # GCA tools (mri_em_register, mri_ca_normalize) expect human-brain intensity
  # scale where WM ~=~ 110. A skull-stripped macaque T1 in UCHAR has WM = 220,
  # making mri_em_register's WM histogram search return "blank" and
  # outputs an empty norm.mgz.
  nu_path <- file_path(fs_root, "mri", "nu.mgz")
  nu_img <- ieegio::read_volume(nu_path)
  nu_data <- nu_img[]
  wm_est <- stats::quantile(nu_data[nu_data > 0], 0.85)
  if (wm_est > 130) {
    scale = 110.0 / wm_est
    ravepipeline::logger("Rescaled nu.mgz: WM {wm_est} -> 110 (factor {sprintf('%.3f', scale)})",
                         use_glue = TRUE, level = "trace")
    nu_data <- round(nu_data * scale)
    nu_data[nu_data < 0] <- 0
    nu_data[nu_data > 255] <- 255
    nu_img[] <- array(as.integer(nu_data), dim = dim(nu_img))
  }
  ieegio::write_volume(nu_img, file_path(fs_root, "mri", "nu.nii.gz"))
  rm(nu_img, nu_data)

  command <- c(
    # Use FreeSurfer to generate nu.mgz
    'echo "====> Converting mri/nu.nii.gz -> mri/nu.mgz"',
    'mri_convert -c "${YAEL_ROOT}/mri/nu.nii.gz" "${YAEL_ROOT}/mri/nu.mgz"',

    # Placeholder norm.mgz: overwritten by mri_ca_normalize later
    'cp "${YAEL_ROOT}/mri/nu.mgz" "${YAEL_ROOT}/mri/norm.mgz"'
  )

  run_freesurfer(command)

  # Talairach registration: use talairach_avi (same as FS 6 autorecon1 internally)
  # Creates proper MNI-format .xfm that all FS tools can parse.
  xfm_path  <- file_path(fs_root, "mri", "transforms", "talairach.xfm")
  xfm_auto  <- file_path(fs_root, "mri", "transforms", "talairach.auto.xfm")
  if (file_exists(xfm_path)) { unlink(xfm_path) }
  if (file_exists(xfm_auto)) { unlink(xfm_auto) }
  # code <- run_freesurfer("talairach_avi --i nu.mgz --xfm transforms/talairach.auto.xfm",
  #                subject = subject, fsdir = fsdir, workdir = "mri")
  #

  # Since we have done it in YAEL, no need to run talairach_avi
  file.copy(file_path(fs_root, "mri", "raw", "affine_x2.xfm"), xfm_auto)

  file.copy(xfm_auto, xfm_path, overwrite = TRUE)

  command <- c(
    'echo "====> Adding transforms/talairach.xfm to headers"',

    'mri_add_xform_to_header -c "${YAEL_ROOT}/mri/transforms/talairach.xfm" "${YAEL_ROOT}/mri/nu.mgz" "${YAEL_ROOT}/mri/nu.mgz"',


    'echo "====> Making binary brainmask"',
    'mri_binarize --i "${YAEL_ROOT}/mri/brainmask_x2.auto.mgz" --min 1 --o "${YAEL_ROOT}/mri/brainmask.auto.mgz"',
    'mri_add_xform_to_header -c "${YAEL_ROOT}/mri/transforms/talairach.xfm" "${YAEL_ROOT}/mri/brainmask.auto.mgz" "${YAEL_ROOT}/mri/brainmask.auto.mgz"',
    'cp "${YAEL_ROOT}/mri/brainmask.auto.mgz" "${YAEL_ROOT}/mri/brainmask.mgz"',

    # =========================================================
    # Build talairach.lta, norm.mgz, and aseg WITHOUT human GCA.
    #
    # The human GCA (RB_all_2016-05-10.vc700.gca) cannot be used with FS 8
    # on a skull-stripped macaque brain: mri_em_register's WM histogram search
    # finds nothing because macaque WM doesn't match human GCA statistics in FS 8,
    # even with fake-space and intensity rescaling. PREEMACS used FS 6 which was
    # more permissive.
    #
    # Instead:
    #  - talairach.lta  : convert talairach.xfm (from talairach_avi) via lta_convert
    #  - norm.mgz       : copy of nu.mgz (WM already ~110 after rescaling)
    #  - aseg.auto_noCCseg.mgz : NMT labels in fake space (macaque-specific, better
    #                    than human GCA labels anyway; still gets replaced by fine-tuned
    #                    NMT labels in Part D for aseg.presurf)
    # =========================================================

    'echo "====> Build talairach.lta + norm.mgz + NMT aseg (no human GCA)"',

    sprintf('lta_convert --inxfm "${YAEL_ROOT}/mri/transforms/talairach.xfm" --outlta "${YAEL_ROOT}/mri/transforms/talairach.lta" --src "${YAEL_ROOT}/mri/nu.mgz" --trg %s', shQuote(mni305)),


    # norm.mgz = nu.mgz (WM ~110 after rescaling; mri_ca_normalize is skipped)
    # No op


    # aseg.auto_noCCseg.mgz from NMT labels in fake space
    'echo "====> Build aseg.auto_noCCseg.mgz from NMT labels (macaque-specific)"',

    # Using `-odt int` to coerce the values
    'mri_convert -rt nearest -odt int -c "${YAEL_ROOT}/mri/raw/aparc+aseg_x2.nii.gz" "${YAEL_ROOT}/mri/aseg.auto_noCCseg.mgz"',
    'cp -f "${YAEL_ROOT}/mri/aseg.auto_noCCseg.mgz" "${YAEL_ROOT}/mri/aseg.auto.mgz"',
    'cp -f "${YAEL_ROOT}/mri/aseg.auto_noCCseg.mgz" "${YAEL_ROOT}/mri/aseg.presurf.mgz"',

    # =========================================================
    # Brain normalization (first half, with GCA aseg.presurf)
    #     M3.sh L228: mri_normalize runs BEFORE NMT label injection.
    #     Control points are derived from GCA labels; NMT replaces them after.
    # =========================================================

    'echo "====> Brain normalization + WM segmentation"',

    # -mprage triggers GCA-based WM calibration; macaque WM statistics don't match
    # the human GCA so that mode always fails. Plain mri_normalize uses aseg WM
    # labels directly and works on any species.
    'mri_normalize -aseg "${YAEL_ROOT}/mri/aseg.presurf.mgz" -mask "${YAEL_ROOT}/mri/brainmask.mgz" "${YAEL_ROOT}/mri/norm.mgz" "${YAEL_ROOT}/mri/brain.mgz"',
    'cp -f "${YAEL_ROOT}/mri/brain.mgz" "${YAEL_ROOT}/mri/brain.finalsurfs.mgz"',

    # WM segmentation (second half, with NMT aseg.presurf)
    'mri_segment -mprage "${YAEL_ROOT}/mri/brain.mgz" "${YAEL_ROOT}/mri/wm.seg.mgz"',

    'mri_edit_wm_with_aseg -keep-in "${YAEL_ROOT}/mri/wm.seg.mgz" "${YAEL_ROOT}/mri/brain.mgz" "${YAEL_ROOT}/mri/aseg.presurf.mgz" "${YAEL_ROOT}/mri/wm.asegedit.mgz"',

    'mri_pretess "${YAEL_ROOT}/mri/wm.asegedit.mgz" wm "${YAEL_ROOT}/mri/norm.mgz" "${YAEL_ROOT}/mri/wm.mgz"',

    ""
  )

  run_freesurfer(command)


  # mri_fill bypass: NMT aseg-based hemisphere labeling
  #
  # mri_fill locates LH/RH seed voxels by back-projecting fixed human Talairach
  # coordinates through talairach.lta. For macaque brains the registration is too
  # distorted and seeds land outside the volume (e.g. "rh seed out of bounds
  # (94, -321, 133)"). We label wm.mgz voxels directly from the NMT aseg which
  # already encodes hemisphere: LH labels -> 255, RH labels -> 127. Any WM voxel
  # not covered by the aseg is assigned by x-RAS sign (x < 0 = LH in FS RAS).
  aseg_img <- ieegio::read_volume(file_path(mri_dir, "aseg.auto_noCCseg.mgz"))
  wm_img   <- ieegio::read_volume(file_path(mri_dir, "wm.mgz"))

  aseg_data <- aseg_img[]
  wm_mask   <- wm_img[] > 0

  # 7:8, 46:47 are cerebellum and 16 is brain-stem We do not wish to include
  # them into the surface
  lh_labels <- c(1:6, 9:15, 17:31)
  rh_labels <- c(40:45, 49:63)

  filled_data <- array(0L, dim = dim(wm_mask))
  filled_data[wm_mask & (aseg_data %in% lh_labels)] <- 255L
  filled_data[wm_mask & (aseg_data %in% rh_labels)] <- 127L

  filled_out <- ieegio::as_ieegio_volume(
    array(as.integer(filled_data), dim = dim(filled_data)),
    vox2ras = wm_img$transforms$vox2ras
  )
  ieegio::write_volume(filled_out, file_path(mri_dir, "filled.nii.gz"))
  rm(filled_out, filled_data, wm_mask, wm_img, aseg_img)

  command <- c(
    'echo "====> filled.nii.gz -> filled.mgz"',
    # mri_convert -odt uchar copies the MGZ geometry (ras2vox, c_ras) from the
    # source so FreeSurfer tools see correct header metadata
    'mri_convert -odt uchar "${YAEL_ROOT}/mri/filled.nii.gz" "${YAEL_ROOT}/mri/filled.mgz"',
    'echo "====> filled.mgz created from NMT aseg (bypassed mri_fill)"',

    # =========================================================
    # Tessellate surfaces  (lh = 255, rh = 127)
    # =========================================================
    'echo "====> Tessellate surfaces  (lh = 255, rh = 127)"',

    # Left - 255
    'mri_pretess "${YAEL_ROOT}/mri/filled.mgz" 255 "${YAEL_ROOT}/mri/norm.mgz" "${YAEL_ROOT}/mri/filled-pretess-255.mgz"',
    'mri_tessellate "${YAEL_ROOT}/mri/filled-pretess-255.mgz" 255 "${YAEL_ROOT}/surf/lh.orig.nofix"',
    'mris_extract_main_component "${YAEL_ROOT}/surf/lh.orig.nofix" "${YAEL_ROOT}/surf/lh.orig.nofix"',

    # Right - 127
    'mri_pretess "${YAEL_ROOT}/mri/filled.mgz" 127 "${YAEL_ROOT}/mri/norm.mgz" "${YAEL_ROOT}/mri/filled-pretess-127.mgz"',
    'mri_tessellate "${YAEL_ROOT}/mri/filled-pretess-127.mgz" 127 "${YAEL_ROOT}/surf/rh.orig.nofix"',
    'mris_extract_main_component "${YAEL_ROOT}/surf/rh.orig.nofix" "${YAEL_ROOT}/surf/rh.orig.nofix"',


    # =========================================================
    # Inflate and fix topology
    # =========================================================
    'echo "====> Inflate + fix topology"',

    'mris_smooth -nw -seed 1234 "${YAEL_ROOT}/surf/lh.orig.nofix" "${YAEL_ROOT}/surf/lh.smoothwm.nofix"',
    'mris_smooth -nw -seed 1234 "${YAEL_ROOT}/surf/rh.orig.nofix" "${YAEL_ROOT}/surf/rh.smoothwm.nofix"',

    'mris_inflate -no-save-sulc "${YAEL_ROOT}/surf/lh.smoothwm.nofix" "${YAEL_ROOT}/surf/lh.inflated.nofix"',
    'mris_inflate -no-save-sulc "${YAEL_ROOT}/surf/rh.smoothwm.nofix" "${YAEL_ROOT}/surf/rh.inflated.nofix"',

    'mris_sphere -q -seed 1234 "${YAEL_ROOT}/surf/lh.inflated.nofix" "${YAEL_ROOT}/surf/lh.qsphere.nofix"',
    'mris_sphere -q -seed 1234 "${YAEL_ROOT}/surf/rh.inflated.nofix" "${YAEL_ROOT}/surf/rh.qsphere.nofix"',

    'cp -f "${YAEL_ROOT}/surf/lh.orig.nofix" "${YAEL_ROOT}/surf/lh.orig"',
    'cp -f "${YAEL_ROOT}/surf/rh.orig.nofix" "${YAEL_ROOT}/surf/rh.orig"',

    'cp -f "${YAEL_ROOT}/surf/lh.inflated.nofix" "${YAEL_ROOT}/surf/lh.inflated"',
    'cp -f "${YAEL_ROOT}/surf/rh.inflated.nofix" "${YAEL_ROOT}/surf/rh.inflated"',

    # folder_name is the FreeSurfer subject ID (SUBJECTS_DIR = imaging_path)
    'mris_fix_topology -mgz -sphere "qsphere.nofix" -ga -seed 1234 "${YAEL_DNAME}" lh',
    'mris_fix_topology -mgz -sphere "qsphere.nofix" -ga -seed 1234 "${YAEL_DNAME}" rh',

    'mris_euler_number "${YAEL_ROOT}/surf/lh.orig"',
    'mris_euler_number "${YAEL_ROOT}/surf/rh.orig"',

    'mris_remove_intersection "${YAEL_ROOT}/surf/lh.orig" "${YAEL_ROOT}/surf/lh.orig"',
    'mris_remove_intersection "${YAEL_ROOT}/surf/rh.orig" "${YAEL_ROOT}/surf/rh.orig"',

    # Remove inflated because we will re-generate
    'rm "${YAEL_ROOT}/surf/lh.inflated"',
    'rm "${YAEL_ROOT}/surf/rh.inflated"',

    # =========================================================
    # White surface (pre-aparc)
    # =========================================================
    'echo "====> White surface (pre-aparc)"',

    'mris_make_surfaces -aseg aseg.presurf -white white.preaparc -noaparc -whiteonly -mgz -T1 brain.finalsurfs "${YAEL_DNAME}" lh',
    'mris_make_surfaces -aseg aseg.presurf -white white.preaparc -noaparc -whiteonly -mgz -T1 brain.finalsurfs "${YAEL_DNAME}" rh',

    'mris_smooth -n 3 -nw -seed 1234 "${YAEL_ROOT}/surf/lh.white.preaparc" "${YAEL_ROOT}/surf/lh.smoothwm"',
    'mris_smooth -n 3 -nw -seed 1234 "${YAEL_ROOT}/surf/rh.white.preaparc" "${YAEL_ROOT}/surf/rh.smoothwm"',

    'mris_inflate "${YAEL_ROOT}/surf/lh.smoothwm" "${YAEL_ROOT}/surf/lh.inflated"',
    'mris_inflate "${YAEL_ROOT}/surf/rh.smoothwm" "${YAEL_ROOT}/surf/rh.inflated"',

    # Curvature stats (required for mris_register)
    'mris_curvature -w "${YAEL_ROOT}/surf/lh.white.preaparc"',
    'mris_curvature -w "${YAEL_ROOT}/surf/rh.white.preaparc"',

    'mris_curvature -thresh .999 -n -a 5 -w -distances 10 10 "${YAEL_ROOT}/surf/lh.inflated"',
    'mris_curvature -thresh .999 -n -a 5 -w -distances 10 10 "${YAEL_ROOT}/surf/rh.inflated"',

    'mris_sphere -seed 1234 "${YAEL_ROOT}/surf/lh.inflated" "${YAEL_ROOT}/surf/lh.sphere"',
    'mris_sphere -seed 1234 "${YAEL_ROOT}/surf/rh.inflated" "${YAEL_ROOT}/surf/rh.sphere"',


    ""
  )

  run_freesurfer(command)

  # =========================================================
  # Surface registration to NMT template
  # =========================================================

  # lh_tif / rh_tif: PREEMACS curvature templates (lh/rh.PREEMACS_34_v1.tif)
  # Set preemacs_dir before running this section.
  tif <- list(
    lh = lh_tif,
    rh = rh_tif
  )
  for (h in c("lh", "rh")) {
    tif_path <- tif[[h]]
    if (!file_exists(tif_path)) {
      message(sprintf("    WARNING: %s not found; copying sphere as sphere.reg", tif_path))
      file.copy(file_path(surf_dir, sprintf("%s.sphere", h)),
                file_path(surf_dir, sprintf("%s.sphere.reg", h)),
                overwrite = TRUE)
      next
    }
    command <- c(
      sprintf('echo "====> Surface registration to NMT template (%s)"', h),

      sprintf('mris_register -curv "${YAEL_ROOT}/surf/%s.sphere" %s "${YAEL_ROOT}/surf/%s.sphere.reg"',
              h, shQuote(tif_path), h),

      sprintf('mris_jacobian "${YAEL_ROOT}/surf/%s.white.preaparc" "${YAEL_ROOT}/surf/%s.sphere.reg" "${YAEL_ROOT}/surf/%s.jacobian_white"', h, h, h),

      #6 selects the 6th frame of the .tif atlas (average curvature map)
      sprintf('mrisp_paint -a 5 %s#6 "${YAEL_ROOT}/surf/%s.sphere.reg" "${YAEL_ROOT}/surf/%s.avg_curv"',
              shQuote(tif_path), h, h)
    )

    run_freesurfer(command)
  }

  # =========================================================
  # Cortical annotation + pial surface  (T1-only; T2 path skipped)
  # =========================================================
  # Human DK atlas GCS for macaque is inaccurate, but coarse labels
  # are sufficient to guide pial surface placement in mris_make_surfaces
  command <- c(
    'echo "====> Cortical parcellation (mris_ca_label)"',
    'echo "      GCS: ${DKT_GCA}"',

    # mris_ca_label [options -seed Seed] <subject> <hemi> <canonsurf> <classifier> <outputfile>
    'mris_ca_label -l "${YAEL_ROOT}/label/lh.cortex.label" -aseg "${YAEL_ROOT}/mri/aseg.presurf.mgz" -seed 1234 "${YAEL_DNAME}" lh "${YAEL_ROOT}/surf/lh.sphere.reg" "${DKT_GCA}" "${YAEL_ROOT}/label/lh.aparc.annot"',

    'mris_ca_label -l "${YAEL_ROOT}/label/rh.cortex.label" -aseg "${YAEL_ROOT}/mri/aseg.presurf.mgz" -seed 1234 "${YAEL_DNAME}" rh "${YAEL_ROOT}/surf/rh.sphere.reg" "${DKT_GCA}" "${YAEL_ROOT}/label/rh.aparc.annot"'
  )

  run_freesurfer(command)

  command <- c(
    'echo "====> Generating Pial surface (*h.pial)"',

    'mris_make_surfaces -orig_white white.preaparc -orig_pial white.preaparc -max 10 -aseg aseg.presurf -mgz -T1 brain.finalsurfs "${YAEL_DNAME}" lh',

    'mris_make_surfaces -orig_white white.preaparc -orig_pial white.preaparc -max 10 -aseg aseg.presurf -mgz -T1 brain.finalsurfs "${YAEL_DNAME}" rh',

    'mris_volmask --aseg_name aseg.presurf --label_left_white 2 --label_left_ribbon 3 --label_right_white 41 --label_right_ribbon 42 --save_ribbon "${YAEL_DNAME}"',


    # =========================================================
    # pial-outer-smoothed
    # =========================================================
    'echo "====> Generating pial-outer-smoothed"',

    'mris_smooth -nw -n 10 "${YAEL_ROOT}/surf/lh.pial" "${YAEL_ROOT}/surf/lh.pial-outer-smoothed"',
    'mris_smooth -nw -n 10 "${YAEL_ROOT}/surf/rh.pial" "${YAEL_ROOT}/surf/rh.pial-outer-smoothed"'
  )

  run_freesurfer(command)

  message(
    "YAEL-tweaked FreeSurfer reconstruction for macaque is done. Please cite:\n\n  ",
    "[1] Wang, Z., Magnotti, J.F., Zhang, X. and Beauchamp, M.S., 2023. ",
    "YAEL: Your advanced electrode localizer. Eneuro, 10(10).\n\n  ",
    "[2] Magnotti, J.F., Wang, Z. and Beauchamp, M.S., 2020. ",
    "RAVE: Comprehensive open-source software for reproducible analysis and ",
    "visualization of intracranial EEG data. NeuroImage, 223, p.117341.\n")


}



#' Run YAEL-based FreeSurfer reconstruction for macaque brains
#'
#' A two-stage pipeline that adapts human cortical reconstruction
#' workflow for \verb{ACPC}-aligned macaque T1w MRI.
#'
#' @param subject character or RAVE subject object. The subject identifier in
#'   \code{"project/subject"} format (e.g. \code{"YAEL/Snorlax"}), or an
#'   object returned by \code{\link{as_rave_subject}}.
#' @param t1w_path character. Absolute path to the T1-weighted NIfTI image
#'   (\code{.nii} or \code{.nii.gz}). Non-NIfTI formats are accepted and will
#'   be converted automatically. Only used by the \code{"normalization"} step.
#' @param folder_name character. Name of the FreeSurfer subject folder created
#'   under the subject imaging directory. Defaults to \code{"fs"}.
#' @param steps character vector. Which stages to run. One or both of
#'   \code{"normalization"} and \code{"reconstruction"}, matched with
#'   \code{\link{match.arg}}. Defaults to both. Pass a single value to resume
#'   from stage 2 without rerunning stage 1.
#'
#' @return Called for its side effects. Returns \code{NULL} invisibly.
#'   On success the FreeSurfer subject directory at
#'   \verb{<imaging_path>/<folder_name>/} is populated with \verb{surf/},
#'   \verb{mri/}, \verb{label/} and related child directories, including
#'   \verb{lh.white}, \verb{rh.white}, \verb{lh.pial}, and \verb{rh.pial}.
#'
#' @details
#'
#' To run this workflow, a dedicated \verb{Python} library and \verb{FreeSurfer}
#' library must be installed. The binaries are not shipped with this package.
#' Please use \code{ravemanager::configure_python()} to configure the
#' \verb{Python} environment. For \verb{FreeSurfer}, version \verb{8.0.0} has
#' been tested. Other versions should work too.
#'
#' \verb{RAVE} looks for \verb{FreeSurfer} using option \code{'freesurfer_path'}
#' and please use \code{ravepipeline::raveio_setopt('freesurfer_path', 'path')}
#' to allow \verb{RAVE} to access the \verb{FreeSurfer} home.
#'
#' The workflow consists of two stages.
#'
#' Stage 1 (\code{"normalization"}) runs
#' YAEL normalization against the \verb{ACPC} aligned \verb{NMT v2} template,
#' crops and rescales the image into a space that satisfies FreeSurfer atlas
#' assumptions, and writes all intermediate imaging inputs under
#' \code{'folder_name/mri/raw/'}. This stage takes around 10 min to run.
#'
#' Stage 2 (\code{"reconstruction"}) drives individual FreeSurfer binaries
#' (no \code{recon-all}) to build white-matter and \verb{pial} surfaces,
#' bypassing steps known
#' to fail on macaque data (human \verb{GCA} atlas registration,
#' \code{mri_fill} seed placement). This stage takes around one to three
#' hours to finish, depending on the computing power and normalization
#' quality.
#'
#'
#' @examples
#'
#' \dontrun{
#' # Full pipeline
#' yael_macaque(
#'   subject  = "YAEL/Snorlax",
#'   t1w_path = "/data/macaque/native_acpc_aligned.nii.gz"
#' )
#'
#' # Resume from reconstruction only (normalization already done)
#' yael_macaque(
#'   subject     = "YAEL/Snorlax",
#'   t1w_path    = "/data/macaque/native_acpc_aligned.nii.gz",
#'   folder_name = "fs",
#'   steps       = "reconstruction"
#' )
#'
#' }

#' @export
yael_macaque <- function(subject, t1w_path, folder_name = "fs", steps = c("normalization", "reconstruction")) {
  steps <- match.arg(steps, several.ok = TRUE)
  if ("normalization" %in% steps) {
    yael_macaque_step1(subject = subject, t1w_path = t1w_path, folder_name = folder_name)
  }
  if ("reconstruction" %in% steps) {
    yael_macaque_step2(subject = subject, folder_name = folder_name)
  }
}





